\\ Generated by qplus1_factordb_campaign.py
\\ FactorDB was used only to discover factors. This GP program reconstructs
\\ the semiprimorials and verifies all arithmetic independently.

is_semiprime_small(k)=
{
  my(F=factor(k), s=0, r);
  r=matsize(F)[1];
  for(i=1,r, s += F[i,2]);
  return(s==2);
};

S=List(); k=4;
while(#S<100, if(is_semiprime_small(k),listput(S,k)); k++);
Q=1; QS=vector(100);
for(i=1,100, Q*=S[i]; QS[i]=Q);


certify_prime(p,tag)=
{
  my(c,f,s);
  if(p < 2^64,
    if(!isprime(p),error(Str(tag,": small primality proof failed")));
    return()
  );
  print("CERTIFY ",tag,"  (",#digits(p)," digits)");
  c=primecert(p);
  if(c==0,error(Str(tag,": primecert() returned 0")));
  if(!primecertisvalid(c),error(Str(tag,": in-memory certificate invalid")));
  if(c[1][1] != p,error(Str(tag,": certificate is for wrong integer")));
  f=fileopen(Str(tag,".cert.gp"),"w");
  filewrite(f,c);
  fileclose(f);
  c=read(Str(tag,".cert.gp"));
  if(!primecertisvalid(c),error(Str(tag,": on-disk certificate invalid")));
  if(c[1][1] != p,error(Str(tag,": on-disk certificate is for wrong integer")));
  s=primecertexport(c,1);
  f=fileopen(Str(tag,".primo"),"w");
  filewrite(f,s);
  fileclose(f);
  print("PROVED ",tag);
};

prove_prime_row(n)=
{
  my(N=QS[n]+1,tag=Str("qplus1_n",n));
  certify_prime(N,tag);
  print("ROW PROVED n=",n," PRIME");
};

prove_semiprime_row(n,a,b)=
{
  my(N=QS[n]+1,tag=Str("qplus1_n",n));
  if(a*b != N,error(Str(tag,": semiprime product mismatch")));
  certify_prime(a,Str(tag,"_f1"));
  certify_prime(b,Str(tag,"_f2"));
  print("ROW PROVED n=",n," SEMIPRIME");
};

prove_nonsemi_row(n,comp,other)=
{
  my(N=QS[n]+1,tag=Str("qplus1_n",n));
  if(comp<=1 || other<=1,error(Str(tag,": trivial nonsemiprime witness")));
  if(comp*other != N,error(Str(tag,": nonsemiprime product mismatch")));
  if(isprime(comp),error(Str(tag,": designated composite part is prime")));
  print("ROW PROVED n=",n," NONSEMIPRIME");
};


prove_prime_row(1);
prove_semiprime_row(2,5,5);
prove_semiprime_row(3,7,31);
prove_prime_row(4);
prove_prime_row(5);
prove_prime_row(6);
prove_nonsemi_row(7,328469,29);
prove_semiprime_row(8,1097,191033);
prove_semiprime_row(9,23,227786087);
prove_nonsemi_row(10,2570114717,53);
prove_prime_row(11);
prove_prime_row(12);
prove_nonsemi_row(13,60103432152809,89);
prove_nonsemi_row(14,614108179881571,331);
prove_prime_row(18);
prove_prime_row(39);
prove_prime_row(51);
prove_nonsemi_row(81,2259506956048492360126014933584069854076893329052649509208003387532926318362226065423283001364517349342035579257358375088177690804453404501319081419624217119,479);
prove_nonsemi_row(83,34893419826693134290151399924222259601018615394147972744068836600886036805476995185236899031372138490192339983552241768202608738525961486726220659145634807,2040511943);
prove_prime_row(98);
prove_nonsemi_row(99,610975441602065462917708758943312495587066226981480368593588800526051467260234530419540808634096856113949333160928436039130888344618752705349470537097541246098438752810306908061725019630996309963099631,271);
print("ALL SETTLED Q_n+1 ROWS RIGOROUSLY PROVED");
quit;
